INSERT INTO CUSTOMER(FIRST_NAME, LAST_NAME) VALUES('John', 'Doe');
INSERT INTO CUSTOMER(FIRST_NAME, LAST_NAME) VALUES('Mike', 'Hassan');
INSERT INTO CUSTOMER(FIRST_NAME, LAST_NAME) VALUES('Chris', 'Jordan');